sudo: required
dist: trusty
language: elixir
otp_release:
  - 20.3
elixir:
  - 1.6.4
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo chmod +x chromedriver
  - sudo mv chromedriver /usr/local/bin
  - nohup chromedriver &
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_install: 
 - npm install npm@latest -g
script:
  - mix test
  - cd assets && npm install
